### ISSUE TITLE
cuda runtime error: the launch timed out and was terminated

### ISSUE THREAD

**Issue by saddy001** [ikostrikov/pytorch-a2c-ppo-acktr#116]
If I'm running the example I get an exception:
```
$ python main.py --env-name "PongNoFrameskip-v4"
...
Updates 0, num timesteps 80, FPS 1392, mean/median reward 0.0/0.0, min/max reward 0.0/0.0, entropy 1.79176, value loss 0.00012, policy loss -0.01562

THCudaCheck FAIL file=/pytorch/aten/src/THC/generated/../THCReduceAll.cuh line=317 error=6 : the launch timed out and was terminated
Traceback (most recent call last):
  File "main.py", line 193, in <module>
    main()
  File "main.py", line 152, in main
    value_loss, action_loss, dist_entropy = agent.update(rollouts)
  File "/home/saddy/Programme/bak/pytorch-a2c-ppo-acktr/algo/a2c_acktr.py", line 75, in update
    self.max_grad_norm)
  File "/home/saddy/miniconda3/envs/tf/lib/python3.6/site-packages/torch/nn/utils/clip_grad.py", line 32, in clip_grad_norm_
    param_norm = p.grad.data.norm(norm_type)
RuntimeError: cuda runtime error (6) : the launch timed out and was terminated at /pytorch/aten/src/THC/generated/../THCReduceAll.cuh:317
```
This is Python 3.6, the latest pytorch-a2c-ppo-acktr, tensorflow 1.10.1, baselines 0.1.5, torch 0.4.1 on CUDA 9.2 with driver 396.54.

**Comment by ikostrikov** [comment]
Still works for me. But I'm using cuda 9.0.

Can anyone with cuda 9.2 confirm the problem?

**Comment by saddy001** [comment]
I launched again with CUDA_LAUNCH_BLOCKING=1. Sometimes, several periods can be trained successfully.
```
...
Updates 190, num timesteps 15280, FPS 1667, mean/median reward -21.0/-21.0, min/max reward -21.0/-21.0, entropy 1.72038, value loss 0.40316, policy loss -0.68720
Updates 200, num timesteps 16080, FPS 1663, mean/median reward -21.0/-21.0, min/max reward -21.0/-21.0, entropy 1.72800, value loss 0.00249, policy loss 0.07607
THCudaCheck FAIL file=/pytorch/aten/src/THC/generated/../THCReduceAll.cuh line=317 error=6 : the launch timed out and was terminated
Traceback (most recent call last):
  File "main.py", line 209, in <module>
    main()
  File "main.py", line 134, in main
    rollouts.masks[step])
  File "/home/saddy/Programme/pytorch-a2c-ppo-acktr/model.py", line 49, in act
    dist_entropy = dist.entropy().mean()
RuntimeError: cuda runtime error (6) : the launch timed out and was terminated at /pytorch/aten/src/THC/generated/../THCReduceAll.cuh:317
```

**Comment by saddy001** [comment]
Problem cause: https://devtalk.nvidia.com/default/topic/1043126/linux/xid-8-in-various-cuda-deep-learning-applications-for-nvidia-gtx-1080-ti/

**Comment by saddy001** [comment]
SO suggests to redesign the code: https://stackoverflow.com/questions/6185117/cudamemcpy-errorthe-launch-timed-out-and-was-terminated
